"""
remediation/generator.py — Main patch generation orchestrator.
 
Flow for each failed/warned check:
  1. If LLM is enabled and API key is available → try LLM
  2. If LLM fails or is disabled → use static template
  3. If no template exists → generate a placeholder with the recommendation text
  4. Write all patches to output_dir/
  5. Write a README.md summarising what was generated and how to apply it
 
The generator is stack-aware: it uses the scan_result.stack_fingerprint
to help the LLM produce more precise patches.
"""
 
from __future__ import annotations
 
import os
import pathlib
import concurrent.futures
import threading
import json
import re
from datetime import datetime, timezone
from dataclasses import dataclass, field
from typing import Optional
 
from sec_audit.results import ScanResult, Status
from sec_audit.config import CHECKS
from remediation.templates import get_template
from remediation.llm import generate_patch_with_llm
 
 
# ── Check metadata index ──────────────────────────────────────────────────────
_CHECK_INDEX: dict[str, dict] = {c["id"]: c for c in CHECKS}
 
 
# ── PatchResult ───────────────────────────────────────────────────────────────
 
@dataclass
class PatchResult:
    """
    A single generated patch file.
 
    Attributes
    ----------
    check_id        The check this patch addresses (e.g. APP-DEBUG-001)
    check_name      Human-readable check name
    layer           Which stack layer (app / webserver / container / host)
    severity        CRITICAL / HIGH / MEDIUM / LOW
    filename        Generated file name (e.g. APP-DEBUG-001.sh)
    file_type       python | shell | nginx | dockerfile | yaml | text
    content         The complete patch file content
    instructions    Step-by-step application instructions
    verification    A command to verify the fix was applied
    is_llm          True if generated by Claude, False if static template
    output_path     Absolute path where the file was written (set after save)
    """
    check_id:     str
    check_name:   str
    layer:        str
    severity:     str
    filename:     str
    file_type:    str
    content:      str
    instructions: str
    verification: str
    is_llm:       bool = False
    output_path:  Optional[pathlib.Path] = field(default=None, repr=False)
 
 
# ── Helpers ──────────────────────────────────────────────────────────────────
 
def _make_target_slug(target: str) -> str:
    """
    Convert a target URL to a short safe slug for use in filenames.
    e.g. "https://admin.example.com/dashboard" → "admin-example-com"
    """
    import re
    # Strip scheme and path, keep hostname
    slug = re.sub(r"https?://", "", target)
    slug = slug.split("/")[0]  # hostname only
    slug = re.sub(r"[^a-zA-Z0-9-]", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug[:40]  # cap length to keep filenames readable
 
 
def _make_patch_header(
    check_id:   str,
    check_name: str,
    target:     str,
    scan_date:  str,
    severity:   str,
    is_llm:     bool,
    file_type:  str,
) -> str:
    """
    Generate an identification header block for every patch file.
    Format adapts to the file type (# for shell/python/nginx, <!-- for html).
    """
    source = "AI-generated" if is_llm else "Standard template"
    lines  = [
        f"StackSentry Patch",
        f"Target:    {target}",
        f"Check:     {check_id} — {check_name}",
        f"Generated: {scan_date}",
        f"Severity:  {severity}",
        f"Source:    {source}",
        f"",
        f"Review this file before applying.",
        f"Shell/Python scripts: run without --apply first (dry run).",
        f"",
    ]
 
    if file_type in ("shell", "python", "nginx", "dockerfile", "yaml", "text"):
        comment_char = "#"
    else:
        comment_char = "#"
 
    header = "\n".join(f"{comment_char} {line}".rstrip() for line in lines)
    return header + "\n\n"
 
 
# ── PatchGenerator ────────────────────────────────────────────────────────────
 
class PatchGenerator:
    """
    Generates remediation patch files for all non-passing checks.
 
    Usage
    -----
        gen = PatchGenerator(use_llm=True, api_key="sk-ant-...")
        results = gen.generate_all(scan_result, output_dir="patches/")
        for r in results:
            print(f"  {r.filename}  ({'LLM' if r.is_llm else 'template'})")
    """
 
    def __init__(
        self,
        use_llm: bool = True,
        api_key: Optional[str] = None,
        verbose: bool = False,
        max_workers: int = 5,
    ):
        self.use_llm     = use_llm
        self.api_key     = api_key or os.environ.get("ANTHROPIC_API_KEY", "")
        self.verbose     = verbose
        self.max_workers = max_workers
        self.max_retries = 2      # retries per LLM call on rate-limit errors
        self.retry_delay = 3.0    # base delay in seconds (doubles each retry)
        self._print_lock = threading.Lock()
 
    # ── Public API ────────────────────────────────────────────────────────────
 
    def generate_all(
        self,
        scan_result: ScanResult,
        output_dir: str = "patches",
    ) -> list[PatchResult]:
        """
        Generate patches for every non-passing check and write them to output_dir.
 
        Returns the list of PatchResult objects, each with output_path set.
        """
        out = pathlib.Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
 
        stack = scan_result.stack_fingerprint
        failing = [c for c in scan_result.checks if c.status != Status.PASS]
 
        if self.verbose:
            with self._print_lock:
                workers = min(self.max_workers, len(failing)) if failing else 1
                mode = "concurrent" if (self.use_llm and self.api_key) else "sequential"
                print(f"[DEBUG] Patch generation: {len(failing)} checks, "
                      f"{workers} workers, {mode} mode")
 
        # ── Concurrent patch generation ────────────────────────────────────
        # Each _generate_one call is independent (LLM call + template lookup),
        # so they can all run in parallel. max_workers=5 is conservative enough
        # to stay well within Anthropic rate limits while being ~5x faster.
        def _generate_and_track(check) -> PatchResult:
            return self._generate_one(
                check.id, check.name, check.layer,
                check.details, check.severity.value, stack,
            )
 
        results: list[PatchResult] = []
        workers = min(self.max_workers, len(failing)) if failing else 1
 
        with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
            # submit preserves submission order; as_completed does not —
            # use futures dict to recover original check order in results
            future_to_check = {
                executor.submit(_generate_and_track, check): check
                for check in failing
            }
            # Collect in completion order (fastest first during generation)
            # then re-sort to original check order before writing
            completed: dict = {}
            for future in concurrent.futures.as_completed(future_to_check):
                check = future_to_check[future]
                try:
                    patch = future.result()
                except Exception as exc:
                    if self.verbose:
                        with self._print_lock:
                            print(f"[DEBUG] Patch {check.id}: exception {exc!r}")
                    patch = self._placeholder(
                        check.id, check.name, check.layer,
                        check.details,
                        _CHECK_INDEX.get(check.id, {}).get("recommendation", ""),
                    )
                    patch = PatchResult(
                        check_id=check.id, check_name=check.name,
                        layer=check.layer, severity=check.severity.value,
                        filename=patch["filename"], file_type=patch["file_type"],
                        content=patch["content"], instructions=patch["instructions"],
                        verification=patch["verification"], is_llm=False,
                    )
                completed[check.id] = patch
 
        # ── Write files in original check order ───────────────────────────
        # Build a short safe slug from the target URL for filename identification
        target_slug = _make_target_slug(scan_result.target)
        scan_date   = datetime.now(tz=timezone.utc).strftime("%Y%m%d")
 
        for check in failing:
            patch = completed[check.id]
 
            # Add target + date to filename so patches are identifiable at scale
            # e.g. HOST-SSH-001_admin-example-com_20260330.sh
            stem, ext = pathlib.Path(patch.filename).stem, pathlib.Path(patch.filename).suffix
            identified_filename = f"{stem}_{target_slug}_{scan_date}{ext}"
            patch.filename = identified_filename
 
            # Prepend identification header to every patch file
            header = _make_patch_header(
                check_id=patch.check_id,
                check_name=patch.check_name,
                target=scan_result.target,
                scan_date=scan_date,
                severity=patch.severity,
                is_llm=patch.is_llm,
                file_type=patch.file_type,
            )
            patch.content = header + patch.content
 
            path = out / patch.filename
            path.write_text(patch.content, encoding="utf-8")
            patch.output_path = path
            results.append(patch)
 
        if results:
            self._write_readme(results, out, scan_result)
            self._write_manifest(results, out, scan_result)
 
        return results
 
    # ── Internal ──────────────────────────────────────────────────────────────
 
    def _generate_one(
        self,
        check_id:   str,
        check_name: str,
        layer:      str,
        details:    str,
        severity:   str,
        stack:      str,
    ) -> PatchResult:
        """
        Generate a single patch using LLM → static template → placeholder fallback.
        """
        cfg          = _CHECK_INDEX.get(check_id, {})
        recommendation = cfg.get("recommendation", "Review and fix this configuration.")
        is_llm       = False
        patch_data   = None
 
        # ── Step 1: Try LLM ───────────────────────────────────────────────────
        if self.use_llm and self.api_key:
            if self.verbose:
                with self._print_lock:
                    print(f"[DEBUG] Patch {check_id}: calling Claude API...")
            patch_data = generate_patch_with_llm(
                check_id=check_id,
                check_name=check_name,
                layer=layer,
                details=details,
                severity=severity,
                stack_fingerprint=stack,
                recommendation=recommendation,
                api_key=self.api_key,
                max_retries=self.max_retries,
                retry_delay=self.retry_delay,
                verbose=self.verbose,
            )
            if patch_data:
                is_llm = True
                if self.verbose:
                    with self._print_lock:
                        print(f"[DEBUG] Patch {check_id}: Claude AI generated {patch_data['filename']}")
            else:
                if self.verbose:
                    with self._print_lock:
                        print(f"[DEBUG] Patch {check_id}: LLM returned None — falling back to template")
 
        # ── Step 2: Static template fallback ─────────────────────────────────
        if not patch_data:
            patch_data = get_template(check_id, details=details, stack=stack)
            if patch_data and self.verbose:
                with self._print_lock:
                    print(f"[DEBUG] Patch {check_id}: using static template → {patch_data['filename']}")
 
        # ── Step 3: Placeholder fallback ─────────────────────────────────────
        if not patch_data:
            if self.verbose:
                with self._print_lock:
                    print(f"[DEBUG] Patch {check_id}: no template found — generating placeholder")
            patch_data = self._placeholder(check_id, check_name, layer,
                                            details, recommendation)
 
        return PatchResult(
            check_id=check_id,
            check_name=check_name,
            layer=layer,
            severity=severity,
            filename=patch_data["filename"],
            file_type=patch_data["file_type"],
            content=patch_data["content"],
            instructions=patch_data["instructions"],
            verification=patch_data["verification"],
            is_llm=is_llm,
        )
 
    @staticmethod
    def _placeholder(
        check_id: str, check_name: str, layer: str,
        details: str, recommendation: str,
    ) -> dict:
        """
        Fallback for checks with no static template and no LLM response.
        Generates a human-readable text file with the recommendation.
        """
        ext = {"app": ".py", "webserver": ".conf",
               "container": ".dockerfile", "host": ".sh"}.get(layer, ".txt")
        return {
            "filename":     f"{check_id}{ext}",
            "file_type":    "text",
            "content": (
                f"# StackSentry — {check_id}: {check_name}\n"
                f"# Layer: {layer}\n\n"
                f"# What was found:\n# {details}\n\n"
                f"# Recommended fix:\n# {recommendation}\n\n"
                f"# No automated patch is available for this check.\n"
                f"# Please apply the fix manually following the recommendation above.\n"
            ),
            "instructions": recommendation,
            "verification": f"Re-run: stacksentry --target <url> (check {check_id} should pass)",
        }
 
    @staticmethod
    def _write_readme(
        results: list[PatchResult],
        output_dir: pathlib.Path,
        scan_result: ScanResult,
    ) -> None:
        """
        Write a README.md to the patches folder explaining what was generated
        and the recommended application order.
        """
        # Sort by severity for recommended application order
        severity_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
        sorted_results = sorted(
            results,
            key=lambda r: severity_order.get(r.severity.upper(), 4),
        )
 
        llm_count      = sum(1 for r in results if r.is_llm)
        template_count = len(results) - llm_count
 
        lines = [
            "# StackSentry — Remediation Patches",
            "",
            f"Generated for: **{scan_result.target}**  ",
            f"Scan date: {scan_result.generated_at[:10]}  ",
            f"Grade: **{scan_result.grade.value}** ({scan_result.score_percentage:.1f}%)  ",
            f"Patches: {len(results)} total "
            f"({llm_count} LLM-generated, {template_count} from templates)",
            "",
            "---",
            "",
            "## How to apply",
            "",
            "Apply patches in the order listed below — higher severity first.",
            "Each patch supports a **dry run** (default) and an **--apply** flag.",
            "",
            "Always dry-run first:",
            "```bash",
            "bash patches/HOST-SSH-001.sh           # preview",
            "bash patches/HOST-SSH-001.sh --apply   # apply",
            "```",
            "",
            "---",
            "",
            "## Patches (recommended application order)",
            "",
            "| # | File | Layer | Severity | Source | Instructions |",
            "|---|------|-------|----------|--------|--------------|",
        ]
 
        for idx, r in enumerate(sorted_results, 1):
            source = "Claude AI" if r.is_llm else "Template"
            instr  = r.instructions[:80] + "..." if len(r.instructions) > 80 else r.instructions
            lines.append(
                f"| {idx} | `{r.filename}` | {r.layer} | {r.severity} "
                f"| {source} | {instr} |"
            )
 
        lines += [
            "",
            "---",
            "",
            "## Verification commands",
            "",
            "After applying each patch, run the corresponding verification command:",
            "",
        ]
 
        for r in sorted_results:
            lines.append(f"**{r.check_id}**: `{r.verification}`  ")
 
        lines += [
            "",
            "---",
            "",
            "## Re-scan after applying fixes",
            "",
            "```bash",
            f"stacksentry --target {scan_result.target} --compare-last",
            "```",
            "",
            "_Generated by StackSentry — https://github.com/stacksentry_",
        ]
 
        readme_path = output_dir / "README.md"
        readme_path.write_text("\n".join(lines), encoding="utf-8")
 
    @staticmethod
    def _write_manifest(
        results: list[PatchResult],
        output_dir: pathlib.Path,
        scan_result,
    ) -> None:
        """
        Write a machine-readable patches/manifest.json so dashboards,
        CI/CD pipelines, and the SaaS tier can discover and process
        patches without parsing individual files.
        """
        manifest = {
            "stacksentry_version": "1.0.0",
            "target":              scan_result.target,
            "scan_date":           datetime.now(tz=timezone.utc).isoformat(),
            "grade":               scan_result.grade.value,
            "score_percentage":    scan_result.score_percentage,
            "total_patches":       len(results),
            "ai_generated":        sum(1 for r in results if r.is_llm),
            "standard":            sum(1 for r in results if not r.is_llm),
            "patches": [
                {
                    "check_id":     r.check_id,
                    "check_name":   r.check_name,
                    "filename":     r.filename,
                    "file_type":    r.file_type,
                    "layer":        r.layer,
                    "severity":     r.severity,
                    "source":       "AI-generated" if r.is_llm else "standard",
                    "instructions": r.instructions,
                    "verification": r.verification,
                    "path":         str(r.output_path) if r.output_path else None,
                    "automatable":  r.layer in ("host", "webserver"),
                }
                for r in results
            ],
        }
        manifest_path = output_dir / "manifest.json"
        manifest_path.write_text(
            json.dumps(manifest, indent=2), encoding="utf-8"
        )
 